# Generated by Django 3.2.5 on 2021-08-06 08:04

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('body', ckeditor.fields.RichTextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
